version: "3.1"
services:
  
  mysql:
    image: mysql:8
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: develop
      MYSQL_ROOT_PASSWORD: secret  # Definir sua senha root desejada aqui

volumes:
  mysql-data:
 
